---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
    indent-sequences: true
  comments:
    min-spaces-from-content: 1
  comments-indentation: {}
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0

ignore: |
  node_modules/
  .git/
  dist/
  build/
  coverage/
